function [fitresult, gof] = createFit(f, avgV)
%CREATEFIT(F,AVGV)
%  Create a fit.
%
%  Data for 'Induced EMF' fit:
%      X Input : f
%      Y Output: avgV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Mar-2019 16:58:57


%% Fit: 'Induced EMF'.
[xData, yData] = prepareCurveData( f, avgV );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Induced EMF' );
h = plot( fitresult, xData, yData );
legend( h, 'V vs. frequency', 'Induced EMF', 'Location', 'NorthEast' );
% Label axes
xlabel 'Frequency(Hz)'
ylabel 'Induced EMF (V)'
grid on


